import * as React from "react";
import { Metadata } from "next";
import { Card, CardContent } from "@/components/ui/card";

export const metadata: Metadata = {
  title: "Kebijakan Privasi",
  description: "Kebijakan Privasi untuk Harga Telur Indonesia. Pelajari bagaimana kami mengumpulkan, menggunakan, dan melindungi data pribadi Anda.",
};

export default function PrivacyPolicyPage() {
  return (
    <main className="flex-1 py-16 sm:py-24 bg-gradient-to-b from-amber-500/5 to-transparent">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <article className="prose prose-zinc dark:prose-invert max-w-none">
          <h1 className="text-4xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-50 mb-4">
            Privacy Policy
          </h1>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-8">
            Last updated: May 27, 2026
          </p>

          <Card className="border border-zinc-200 dark:border-zinc-800 bg-white/50 backdrop-blur-sm mb-8">
            <CardContent className="pt-6 text-zinc-700 dark:text-zinc-300 leading-relaxed space-y-4">
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>
              <p>
                We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
            </CardContent>
          </Card>

          <div className="space-y-8 text-zinc-700 dark:text-zinc-300 leading-relaxed">
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mt-6 mb-3">Interpretation and Definitions</h2>
              <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-4 mb-2">Interpretation</h3>
              <p>
                The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>
              
              <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-4 mb-2">Definitions</h3>
              <p className="mb-2">For the purposes of this Privacy Policy:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Harga Telur Indonesia.</li>
                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><strong>Country</strong> refers to: Indonesia</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                <li><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual. We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</li>
                <li><strong>Service</strong> refers to the Website.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>Website</strong> refers to Harga Telur Indonesia, accessible from hargatelurindonesia.com.</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mt-6 mb-3">Collecting and Using Your Personal Data</h2>
              <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-4 mb-2">Types of Data Collected</h3>
              
              <h4 className="text-lg font-bold text-zinc-900 dark:text-zinc-100 mt-3 mb-1">Personal Data</h4>
              <p className="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
              <ul className="list-disc pl-6 space-y-1 mb-4">
                <li>Email address</li>
                <li>Usage Data</li>
              </ul>

              <h4 className="text-lg font-bold text-zinc-900 dark:text-zinc-100 mt-3 mb-1">Usage Data</h4>
              <p className="mb-4">
                Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p className="mb-4">
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              </p>
              <p>
                We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-6 mb-2">Tracking Technologies and Cookies</h3>
              <p className="mb-4">
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
              </p>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
              </ul>
              <p className="mb-4">
                Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
              </p>
              <p className="mb-4">
                Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.
              </p>
            </section>

            {/* Google Ads and Remarketing Services (NEW SECTION ADDED AS REQUESTED) */}
            <section className="p-6 rounded-xl bg-amber-500/5 border border-amber-500/20 dark:bg-amber-950/10 dark:border-amber-900/30 my-8">
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mt-0 mb-3">Google Ads & Remarketing Services</h2>
              <div className="space-y-4">
                <p>
                  <strong>Google AdSense & Advertising:</strong> We display advertisements on our Website provided by Google Ads (Google AdSense) and other third-party networks. Google uses cookies (such as the DoubleClick cookie) to serve ads to users based on their visits to our Website and other websites on the Internet. You may opt out of personalized advertising by visiting Google's <a href="https://adssettings.google.com" target="_blank" rel="noopener noreferrer" className="text-amber-600 dark:text-amber-400 hover:underline">Ads Settings</a>.
                </p>
                <p>
                  <strong>Remarketing Services:</strong> We use remarketing services to advertise our business to You on third party websites after You have visited our Website. We and our third-party vendors use cookies to inform, optimize, and serve ads based on Your past visits to our Website. This helps us provide targeted, relevant information to users who have shown interest in egg prices and farming updates.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mt-6 mb-3">Use of Your Personal Data</h2>
              <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                <li>To provide You with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</li>
                <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                <li>For business transfers: We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mt-6 mb-3">Retention of Your Personal Data</h2>
              <p className="mb-4">
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </p>
              <p className="mb-4">
                Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods (&quot;up to&quot;) and We may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:
              </p>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li><strong>User Accounts:</strong> retained for the duration of your account relationship plus up to 24 months after account closure.</li>
                <li><strong>Customer Support Data:</strong> up to 24 months from the date of ticket closure or support interaction.</li>
                <li><strong>Usage Data:</strong> Website analytics data and server logs are retained for up to 24 months from the date of collection.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mt-6 mb-3">Delete Your Personal Data</h2>
              <p>
                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service or You may contact Us directly to request access to, correct, or delete any Personal Data that You have provided to Us.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mt-6 mb-3">Security of Your Personal Data</h2>
              <p>
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mt-6 mb-3">Links to Other Websites</h2>
              <p>
                Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mt-6 mb-3">Contact Us</h2>
              <p className="mb-2">If you have any questions about this Privacy Policy, You can contact us:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>By phone: +62 822-3009-5517</li>
                <li>By email: info@hargatelur.id</li>
              </ul>
            </section>
          </div>
        </article>
      </div>
    </main>
  );
}
